### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by Rocks360** [irkanu/simple-facebook-page-widget#5]
I get this Issue if I try the Widget

Notice: Undefined index: app_id in /Applications/MAMP/htdocs/wordpress-4/wp-content/plugins/simple-facebook-twitter-widget/simple-facebook-page-plugin.php on line 170

**Comment by irkanu** [comment]
Good catch! Should be fixed now.

**Comment by Rocks360** [comment]
thank you! 😊
