### ISSUE TITLE
Load Facebook Page Plugin Asynchronously

### ISSUE THREAD

**Issue by OC2PS** [irkanu/simple-facebook-page-widget#7]
Facebook social plugins slow down page load, eroding user experience. Load the Page Plugin JS asynchronously. See hints at http://www.pcsteps.com/3260-add-facebook-page-plugin-asynchronous-code/

**Comment by irkanu** [comment]
My latest commit loads the page plugin javascript asynchronously. See commit https://github.com/irkanu/simple-facebook-page-widget/commit/be7e0206529a9ae37817c646707cab289f0c1094

If you'd like to see it handled differently, then please submit a pull request with the code modified to your liking. :)

I'd be happy to review it. :+1:
