### ISSUE TITLE
Use language parameter

### ISSUE THREAD

**Issue by OC2PS** [irkanu/simple-facebook-page-widget#8]
Facebook allows you to set the language https://developers.facebook.com/docs/plugins/page-plugin#language

So you can simply grab WordPress's language setting and use that as a parameter while grabbing the Page Plugin to make the plugin multilingual.

**Comment by irkanu** [comment]
I'm curious if you have downloaded and installed the plugin.

You can see the on the settings page for the plugin the ability to select a language for the page plugin itself. That option is then stored in the database and passed to the javascript here: https://github.com/irkanu/simple-facebook-page-widget/blob/master/js/simple-facebook-page-root.js#L7

If you feel like there is a better solution, then please submit a pull request with your purposed changes and I'd love to look it over. :)

**Comment by OC2PS** [comment]
In all honesty, I have not. Have only seen screenshots, description and support threads. Trying to figure out whether it's worth dumping my current plugin in favor of this.

The setting for languages as of now is not great as it is not suitable for multilingual sites. While it may work for sites in non-English languages, it doesn't work for sites with multiple languages. 

An alternate approach would be to grab the language from WordPress page.

Another approach could be to set language at widget level instead of plugin settings level. Similarly, language could be passed on as a parameter in shortcodes.
